CREATE TABLE IF NOT EXISTS ad_files (

ad_id BIGINT REFERENCES ad (ad_id) ON UPDATE CASCADE ON DELETE CASCADE,
file_id UUID REFERENCES files (file_id) ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT ad_files_pkey PRIMARY KEY (ad_id, file_id)

);