CREATE TABLE IF NOT EXISTS files (

file_id UUID NOT NULL PRIMARY KEY,
name VARCHAR(255) NOT NULL,
url VARCHAR(255) NOT NULL

);

CREATE TABLE IF NOT EXISTS ad_images (

ad_id BIGINT REFERENCES ad (ad_id) ON UPDATE CASCADE ON DELETE CASCADE,
file_id UUID REFERENCES files (file_id) ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT ad_files_pkey PRIMARY KEY (ad_id, file_id)

);